-- SQLite
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    Email VARCHAR(32) UNIQUE NOT NULL,
    FirstName VARCHAR(32) NOT NULL,
    LastName VARCHAR(32) NOT NULL,
    Password VARCHAR(128) NOT NULL,
    id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL);



DROP TABLE IF EXISTS products;

CREATE TABLE IF NOT EXISTS products (
    Name VARCHAR(32) NOT NULL,
    Description VARCHAR(300) NOT NULL,
    Price INTEGER(5)NOT NUll CHECK(price >= 0),
    img VARCHAR(256),
    id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL);